
export const ADD_USER = "ADD_USER"
export const USER_CREATED="USER_CREATED"
export const USERS_LIST = "USERS_LIST"
export const SEND_MESSAGE = "SEND_MESSAGE"
export const MESSAGE_SENT="MESSAGE_SENT"
export const GET_MESSAGES = "GET_MESSAGES"
export const CLEAR_MESSAGES="CLEAR_MESSAGES"
export const GET_ROOMS = "GET_ROOMS"
export const ROOM_LIST="ROOM_LIST"
export const CREATE_ROOM = "CREATE_ROOM"
export const JOIN_ROOM = "JOIN_ROOM"
export const ENTER_ROOM="ENTER_ROOM"
export const USER_PROPORTIES="USER_PROPORTIES"

